window.defaultNumber = '+1-855-657-5112  ';
window.defaultText = 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you?<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !';
window.text = {
    'xhamster.com': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !',
    'perfectgirls.net': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !',
    'gotporn.com': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !',
    'anysex.com': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !',
    'sex.com': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   unlock it !',
    'bravotube.net': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !',
    'mylust.com': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !',
    'manporn.xxx': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !',
    'anybunny.com': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !',
    'txxx.com': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !',
    'findbestsolution.xyz': 'Your Apple ID was recently used at APPLE STORE for $249.99 Via Apple Pay Pre-Authorization! We have placed those request on hold to ensure safety and security.Not you? on |%ref%|!<br>Immediately call Customer Support<br>+1-855-657-5112   to Freeze it! !'
};
